server:
  port: 8888
  servlet:
    session:
      cookie:
        http-only: true
        #secure: true   # 表示尽可以通过https来送cookie

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sectest?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: chen2908
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    cache: false    # 缓存默认是关闭的
    suffix: .html  # 模板的后缀名，模认是ftl
    charset: utf-8  # 文件编码
    template-loader-path: classpath:/templates/
  security:
    logintype: JSON
#    user:
#      name: admin
#      password: admins